// examples/svelte/src/lib/components/form.svelte
<script context="module" lang="ts">
  import { validateForm, setFormData } from "@vardario/zod-form-validation";
</script>

<script lang="ts">
  import type { ZodAny, AnyZodObject, z, ZodEffects } from "zod";
  import type { PartialDeep } from "type-fest";

  type T = $$Generic<AnyZodObject | ZodAny | ZodEffects<AnyZodObject>>;
  type ObjectType = z.infer<typeof schema>;

  export let schema: T;
  export let data: PartialDeep<ObjectType> | undefined = undefined;

  let form: HTMLFormElement;

  function formValidation(_form: HTMLFormElement) {
    form = _form;
    if (schema) {
      validateForm(_form, schema);
    }
  }

  $: form && data && setFormData(form, data);
</script>

<form use:formValidation {...$$props}>
  <slot />
</form>

// examples/next/src/components/form.tsx
"use client";

import { HTMLAttributes, PropsWithChildren, useEffect, useRef } from "react";
import { z } from "zod";
import { PartialDeep } from "type-fest";
import { validateForm, setFormData } from "@vardario/zod-form-validation";

export interface FormProps<TSchema extends z.ZodSchema, TData = unknown>
  extends PropsWithChildren<HTMLAttributes<HTMLFormElement>> {
  schema?: TSchema;
  data?: PartialDeep<TData>;
}

export default function Form<
  TSchema extends z.ZodSchema,
  TData = z.infer<TSchema>
>({ children, schema, data, ...props }: FormProps<TSchema, TData>) {
  const formRef = useRef<HTMLFormElement>(null);

  useEffect(() => {
    if (schema) {
      validateForm(formRef.current!, schema);
    }
  }, [formRef, schema]);

  useEffect(() => {
    if (data && schema) {
      setFormData(formRef.current!, data);
    }
  }, [formRef, data, schema]);

  return (
    <form ref={formRef} {...props}>
      {children}
    </form>
  );
}
