// examples/svelte/src/lib/components/textarea.svelte
<script lang="ts">
  import { observerValidationErrors } from "@vardario/zod-form-validation";

  export let label: string | undefined = undefined;
  let errors: string[] = [];

  function enhance(input: HTMLTextAreaElement) {
    observerValidationErrors(input, (_errors) => {
      errors = _errors;
    });
  }
</script>

<div class="flex flex-col gap-2">
  <div class="flex flex-col-reverse gap-2">
    <textarea
      use:enhance
      class="p-2 valid:border rounded outline-none invalid:outline invalid:outline-red-600 outline-1 peer"
      id={$$props.name}
      {...$$props}
    />
    {#if label}
      <label
        class="peer-data-[validation-required=true]:after:content-['*'] after:text-red-500 text-sm"
        for={$$props.name}
      >
        {label}
      </label>
    {/if}
  </div>

  {#each errors as error}
    <span class="text-sm text-red-600">
      {error}
    </span>
  {/each}
  <div />
</div>

// examples/next/src/components/textarea.tsx
'use client';

import { observerValidationErrors } from '@vardario/zod-form-validation';
import { PropsWithChildren, TextareaHTMLAttributes, useEffect, useRef, useState } from 'react';

export interface TextAreaProps extends PropsWithChildren<TextareaHTMLAttributes<HTMLTextAreaElement>> {
  label?: string;
}

export default function Textarea({ label, children, ...props }: TextAreaProps) {
  const [errors, setError] = useState<string[]>([]);
  const inputRef = useRef<HTMLTextAreaElement>(null);

  useEffect(() => {
    observerValidationErrors(inputRef.current!, _errors => {
      setError(_errors);
    });
  }, [inputRef]);

  return (
    <div className="flex flex-col gap-2">
      <div className="flex flex-col-reverse gap-2">
        <textarea
          ref={inputRef}
          className="peer rounded p-2 outline-none outline-1 valid:border invalid:outline invalid:outline-red-600"
          id={props.name}
          {...props}
        >
          {children}
        </textarea>
        {label && (
          <label
            className="text-sm after:text-red-500 peer-invalid:text-red-500 peer-data-[validation-required=true]:after:content-['*']"
            htmlFor={props.name}
          >
            {label}
          </label>
        )}
      </div>
      {errors.map((error, index) => (
        <span key={index} className="text-sm text-red-600">
          {error}
        </span>
      ))}
      <div />
    </div>
  );
}
